name: QMetry Upload Test

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show file info
        run: ls -lh results/

      - name: Upload Junit Results to QMetry
        run: |
          curl --silent --show-error --write-out "\nStatus: %{http_code}\n" \
            --location 'https://testmanagement.qmetry.com/rest/import/createtestscheduleresults/1' \
            --header 'project: MAC' \
            --header 'apikey: 080G6UpJ57ix4JKNn0hlMtDvhvE6E4BKfQ4saaH2' \
            --form entityType=JUNIT \
            --form file=@results/Scenario1.xml
